name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up C++ toolchain
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake cppcheck clang-format

      # Run static code analysis using cppcheck
      - name: Static analysis (cppcheck)
        run: |
          cppcheck --enable=all --inconclusive --std=c++17 --force . 2> cppcheck-report.txt || true

      # Upload cppcheck results as an artifact (Corrected indentation)
      - name: Upload cppcheck report
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-report
          path: cppcheck-report.txt

      # Run linting on C++ files using clang-format
      - name: Lint C++ files (clang-format)
        run: |
          find . -name '*.cpp' -o -name '*.hpp' | xargs clang-format -i

      # Run linting on CMake files using cmakelint
      - name: Install pip and cmakelint
        run: |
          sudo apt-get install -y python3-pip
          pip install cmakelint

      - name: Lint CMake files
        run: |
          find . -name 'CMakeLists.txt' -o -name '*.cmake' | xargs cmakelint

      # Build the project using CMake
      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake
        run: cmake -S . -B build

      - name: Build with CMake
        run: cmake --build build
